import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider as Auth0Provider } from "@auth0/nextjs-auth0/client";

import "./globals.scss";
import { UserProvider } from "./[user]/useAuth";
import Navigation from "./_components/Navigation";
import { Container } from "react-bootstrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Auth0Provider>
          <UserProvider>
            <Navigation />
            <Container className="my-4">{children}</Container>
          </UserProvider>
        </Auth0Provider>
      </body>
    </html>
  );
}
